### ISSUE TITLE
Add support for Snipcart’s modal-style option

### ISSUE THREAD

**Issue by sampsonpete** [nuxt-community/snipcart-module#10]
Snipcart has an [option to change the modal style to _side_ using a data attribute](https://docs.snipcart.com/v3/setup/installation#data-config-modal-style) but it doesn‘t seem to be accessible in this module’s options. 

I’m guessing that the only way to enable it now would be to add Snipcart manually instead of using this module but it would be great if it were added as an option.

**Comment by f3ltron** [comment]
Hello @sampsonpete ! Thank's for using the module and open issue :).

You mean instead of full page having it on side only ?

**Comment by f3ltron** [comment]
Ok it's corrected with version 1.1.1.

https://snipcart.nuxtjs.org/setup/#attributes 

Now you can add more data-entry if needed. I am closing for now.

If you still have the bug re open it @sampsonpete

**Comment by sampsonpete** [comment]
That’s exactly what I meant, @f3ltron. Thanks for addressing it so quickly!

**Comment by f3ltron** [comment]
Top don't hesitate to ask if you need more. I could have forget things but I think now I cover a lot. 

Enjoy the module :)
