### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 in Chrome

### ISSUE THREAD

**Issue by henrikhansson** [nuxt-community/snipcart-module#12]
After installing the package Chrome is throwing errors when running "npm run dev"

GET http://localhost:3000/__webpack_hmr/client net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

This is causing a complete NUXT re-build every time. I have double checked and it is 100% the Snipcart package causing this error.

**Comment by f3ltron** [comment]
Hello @henrikhansson  Thank's for your issue. Can you give me a repo so I can try it and try to repro, please as I don't have the error.

Can you also specify:

nuxt version
snipcart version if you don't use the default one

Thank's again :)

**Comment by henrikhansson** [comment]
Hi!

I was on Nuxt 12.2 but upgraded to 2.14 but the issue persisted. Default Snipcart version.
I will try find time to build a repo, but it might take me a few days. In the meantime I will re-build the project with the issues and try to note when the issues appear.

Three other things:

* How do you specify :data-item-max-quantity in customFields? Tried a few different variations without luck.
* The customFields does not seem to work dynamic. If I update a field, for example with a select, the initial value is forwarded to the cart. (Product loads with text "Hey", I choose "You", press add to cart and text "Hey" is put in the cart). It works fine with the old way of binding fields
 
```
data-item-custom1-name="Readonly information"
data-item-custom1-type="readonly"
data-item-custom1-value="This is a readonly custom field">
```

* Lastly, I cannot get my NUXT installation to accept the unidentified variable window.Snipcart, got any magic tricks?

**Comment by f3ltron** [comment]
Yeah if you can have a repo example would be great. 

-If you are using like my example it should work https://snipcart.nuxtjs.org/utils#customfields. 
- It should be reactive if you handle well the array like 
  this.customField === [...customfields, other]
  Probably you didn't handle good the reactivity

- Where do you try to call window.Snipcart?

I think it really need a repo here :s. I can't do more here @henrikhansson

**Comment by henrikhansson** [comment]
Hi,

I’m sorry I haven’t been able to get a repo ready, overworked at the moment and fell back to include the js files instead. Will let you know asap when I find time to build a repo!

// Henrik




Henrik Hansson
p.henrik.hansson@icloud.com

**Comment by sampsonpete** [comment]
Hi @f3ltron I’ve just started using the module properly and am seeing this same issue. When the Snipcart module is installed and `npm run dev` is run, each time you save a change to the code Nuxt tries to regenerate the app and that error appears in the console.

I’ve created a reduced test case example where you can see it happening in this repo: https://github.com/sampsonpete/nuxt-snipcart-test

Thanks, let me know if you need any more information.

**Comment by sampsonpete** [comment]
Hi @f3ltron, sorry for the delay in replying – I can confirm that I don’t see this error anymore after installing the latest version (1.2.2).

**Comment by f3ltron** [comment]
No problem. Awesome
