### ISSUE TITLE
migrate to nuxt-community

### ISSUE THREAD

**Issue by pi0** [nuxt-community/snipcart-module#2]
- [x] Review code by framework team (@pi0 @Atinux @clarkdo)
- [x] Send NPM invitation
- [x] Send nuxt-community invitation
- [x] Move repository to `nuxt-community`
- [x] Update all references to `@nuxtjs/snipcart`
- [x] Publish `@nuxtjs/snipcart`
- [x] ~~Deprecate `nuxt-snipcart` npm package~~ (seems never published)
- [x] Teardown current netlify website
- [x] Deploy snipcart.nuxtjs.org
- [ ] Add to modules.nuxtjs.org

**Comment by f3ltron** [comment]
@pi0 If you can validate.

I have moved normally all references to @nuxtjs/snipcart and snipcart-module repo

Tell me if you need more info or correcting things

**Comment by pi0** [comment]
@f3ltron Migration should be almost done. Please let me know when accepted npm invitation so i can adjust team. It would be nice if you can remove old published website. I will also add it to modules website after a while. I think also it is faster if you freshly clone new repository since nested node_modules changed.

**Comment by f3ltron** [comment]
The invitation is accepted
I have deleted the netlify website.

**Comment by f3ltron** [comment]
I think we are pretty good now. Thank's @pi0  :). I will publish my article soon

**Comment by pi0** [comment]
Thanks @f3ltron NPM team is also updated. Good luck :+1:
