### ISSUE TITLE
Currencies configuration

### ISSUE THREAD

**Issue by kbrosseau** [nuxt-community/snipcart-module#25]
Hi, 

Is there a way to configure currencies with this module.
According to snipcart documentation, we have to deal with js : Snipcart.api.session.setCurrency('usd');

Maybe an easier way with this module?

Thanks,
Kevin

**Comment by f3ltron** [comment]
Hey can you send me the link to the doc please

**Comment by f3ltron** [comment]
without checking more the code you may be able to achieve it as i am doing with event. by using 

`window.Snipcart.api.session.setCurrency('usd');` when snipart is ready https://snipcart.nuxtjs.org/events

**Comment by kbrosseau** [comment]
Hi, thanks i tried that way to integrate with nuxt i18n like this 
`    mounted () {
      document.addEventListener('snipcart.ready', function () {
        window.Snipcart.events.on(window.Snipcart.api.session.setCurrency(this.$i18n.localeProperties.currency))
      })
    },`
But it does not work

**Comment by kbrosseau** [comment]
But it is strange because without i18n localproperties it is working
`    mounted () {
      const currency = context;
      document.addEventListener('snipcart.ready', function () {
        window.Snipcart.events.on(window.Snipcart.api.session.setCurrency('usd')
      })
    },`

**Comment by f3ltron** [comment]
But the currencies is linked with the locale no ? Long time i didn't work with it but I think it's already work if you change the locale

**Comment by kbrosseau** [comment]
Yes currencies is linked with the local, but it is not linked to snipcart. According to snipcart documentation, we have to setting cart currency in two way : 
- `<div hidden id="snipcart" data-api-key="<API_KEY>" data-currency="usd"></div>` => We have not access to it with nuxt/snipcart extension.
- `Snipcart.api.session.setCurrency('usd');`

**Comment by kbrosseau** [comment]
To be dynamic, we have to integrate nuxt/snipcart with nuxt/i18n like this : 
`mounted () { document.addEventListener('snipcart.ready', function () { window.Snipcart.events.on(window.Snipcart.api.session.setCurrency(this.$i18n.localeProperties.currency)) }) },`

But it does not work, waybe my code is wrong?

**Comment by f3ltron** [comment]
tell me if its ok for you but should work with this pr https://github.com/nuxt-community/snipcart-module/pull/28

**Comment by f3ltron** [comment]
@kbrosseau  if you follow https://snipcart.nuxtjs.org/events

with the pr merged you will have everything you need
