### ISSUE TITLE
Have an access to $snipcart.setCurrency()

### ISSUE THREAD

**Issue by kbrosseau** [nuxt-community/snipcart-module#26]
Hi everyone,

It will be usefull to have an access to $snipcart.setCurrency() (in the same way as "$snipcart.setLanguage()")

Here is the documentation of snipcart : https://docs.snipcart.com/v1/javascript-api/public-api#getcurrentcurrency

Have a good day,
Kevin

**Comment by f3ltron** [comment]
Sounds like #25 . I will keep both. Will look at it when I have time

**Comment by eliascarella** [comment]
Hi, any news on this feature ?

**Comment by f3ltron** [comment]
Ok i have time to look at it. But this feature is from v1 no?

**Comment by f3ltron** [comment]
Perfect ! thank you a lot for your work.

close #28

**Comment by f3ltron** [comment]
https://github.com/nuxt-community/snipcart-module/pull/28
