### ISSUE TITLE
No Nuxt 3 Comptabile version ?

### ISSUE THREAD

**Issue by Celibioux** [nuxt-community/snipcart-module#37]

**Comment by jsbaguette** [comment]
Hello @Celibioux. Thats a good question. As it's not my full time job. I will wait for nuxt team have a better documentation on module transtion to nuxt3.

I will keep up to date here. Don't hesitate to give me documentation :)

**Comment by Celibioux** [comment]
https://v3.nuxtjs.org/docs/advanced/modules

I wish I could help more ! ( but i’m not too powerful - still learning 😔 )

**Comment by jsbaguette** [comment]
I will try to have a quick look about it this weekend :) Thanks for the doc.

On your side don't hesitate to tell me if I am missing some features from snipcart would be really helpful

**Comment by Celibioux** [comment]
@jsbaguette acctualy i think that you did a greate work with the module so far i liked working with it on the Nuxt 2 version ( just one thing was little hard not clear is the abality to customizing the ui components of strapi ) thanks again for your great work

**Comment by baermathias** [comment]
Just wanted to ask if there was any progress made with Nuxt 3?

**Comment by Joaojack** [comment]
Same question - are there any plans for a Nuxt 3 integration ? Thanks !

**Comment by flozero** [comment]
alright. I know it has been a long time but just so you know I will start to work on a nuxt 3 version

**Comment by Joaojack** [comment]
Good luck with this project!

**Comment by flozero** [comment]
Alright the next branch is working I will put it on BETA I will explain what is the TODO list to pass the BETA

https://github.com/nuxt-community/snipcart-module/tree/next

**Comment by flozero** [comment]
Alright happy to announce nuxt 3 support finished. Some of the existing function helpers still exists but we don't have quite fully backward compatibility.

So please take time to read the release :) https://github.com/nuxt-community/snipcart-module/releases/tag/v2.0.0

Now we have better configuration for loading css or js:
- https://github.com/nuxt-community/snipcart-module/issues/43 @gkurl 

The dev environment thanks to nuxt3 will be way nicer that make the component customization really cool to work with
- @Joaojack 
- @deodat
- @andreavigani 

Memory leak will not be a problem anymore normally
- @sampsonpete

Hope you will enjoy this new package don't hesitate to create PR or Issue base on what you face
