### ISSUE TITLE
Overridable component customization not working

### ISSUE THREAD

**Issue by andreavigani** [nuxt-community/snipcart-module#38]
I created the _customize.js_ file, and placed it in the root folder _/snipcart_.
![image](https://user-images.githubusercontent.com/6072750/152144543-7270e86e-457c-4bfe-82ba-6cd91c72fe90.png)

The following code in customize.js should add an h3 html tag in the header of the "order thank you page" but nothing is showing up:

`module.exports = '<order section="header"><cart-header class="snipcart-checkout__header" :show-items-count="false" :show-summary="false" :show-account-menu="false"></cart-header><h3>MY CUSTOM HTML CODE</h3></order>'`

This is the reference for order page customization: https://docs.snipcart.com/v3/themes/default/reference#component-order
And this is the overridable component section
![image](https://user-images.githubusercontent.com/6072750/152143635-7d3e6ff6-2df0-4555-902c-ccb886929f6b.png)

The snipcart folder also includes customize.css file, the style customization is working as expected.

I also take a look at the example but it seems to me that nothing else is missing. 
Any suggestion?

Thanks

**Comment by jsbaguette** [comment]
Hello @andreavigani I am surprise it doens't work. Going to have a quick look this weekend if you can provide me an example folder please

**Comment by deodat** [comment]
Hello, any news on this?
I have the same problem with:
```
module.exports = `
<billing section="bottom">
    <fieldset class="snipcart-form__set">
        <div class="snipcart-form__field">
            <snipcart-label class="snipcart__font--tiny" for="customMessage">
                Message personnalisé
            </snipcart-label>
            <snipcart-textarea class="snipcart-textarea" name="customMessage"></snipcart-textarea>
        </div>
    </fieldset>
</billing>

<payment section="top">
<div>
    <p>
        <snipcart-checkbox name="privacy-policy" required></snipcart-checkbox>
        <snipcart-label for="privacy-policy">J&#39;accepte les&nbsp;<a href="#" class="snipcart-link">conditions générales de vente</a></snipcart-label>
    </p>
</div>
</payment>
`
```

**Comment by deodat** [comment]
I tried to add the path in `nuxt.config.js`like this:
```
  snipcart: {
    key: process.env.SNIPCART_API_KEY,
    snipcartCustomize: '/snipcart/customize',
    ...
```
but without success.

What is weird is that my override used to work.
Maybe it's a related to a change in Snipcart?
I have this warning in my console by the way which I think I did not have before:
```
window.SnipcartSettings` is not defined. Consider using the latest installation instructions (https://docs.snipcart.com/v3/setup/installation). | snipcart.js:1 
```

**Comment by link82** [comment]
I had the same problem, after some tests I decided to temporary remove the module and integrate Snipcart manually.

**Comment by deodat** [comment]
Thanks for the feedback @link82! 
I think I'm gonna do the same.

**Comment by deodat** [comment]
Hello,

I finally managed to get this working with an example found in Snipcart forum:
https://support.snipcart.com/t/localize-in-custom-components-gives-error-in-nuxt-project/610
https://codesandbox.io/s/nuxt-customization-external-templates-4tj4b?file=/static/snipcart-templates.html

Here is the code for `nuxt.config.js` :
```
  buildModules: ["@nuxtjs/snipcart"],

  snipcart: {
    key: "MzMxN2Y0ODMtOWNhMy00YzUzLWFiNTYtZjMwZTRkZDcxYzM4",
    version: "v3.2.2",
    attributes: [["data-templates-url", "/snipcart-templates.html"]]
  },
```

and an example of override in `/static/snipcart-templates.html`:
```
<div id="snipcart-templates">
  <address-fields>
    <div>
      <fieldset class="snipcart-form__set">
        <div class="snipcart-form__row">
          <div class="snipcart-form__field snipcart-form__cell--large">
            <snipcart-label class="snipcart__font--tiny" for="address1"
              >{{ $localize('address_form.address1') }}</snipcart-label
            >
            <snipcart-input name="address1"></snipcart-input>
            <snipcart-error-message name="address1"></snipcart-error-message>
          </div>

          <div class="snipcart-form__field snipcart-form__cell--tidy">
            <snipcart-label class="snipcart__font--tiny" for="address2"
              >{{ $localize('address_form.address2') }}</snipcart-label
            >
            <snipcart-input name="address2"></snipcart-input>
            <snipcart-error-message name="address2"></snipcart-error-message>
          </div>
        </div>
      </fieldset>
    </div>
  </address-fields>
</div>
```

This is working for me :)

**Comment by flozero** [comment]
thank you @deodat  I will close for now and see how to explain or implement this on the nuxt 3 version
