### ISSUE TITLE
Some way to force load after all other JS?

### ISSUE THREAD

**Issue by gkurl** [nuxt-community/snipcart-module#43]
Hi sorry the cart modal works - changing question: I'm just wondering if there is a way to load this after all other JS has been loaded, as the snipcart JS seems to be interferring with other JS scripts I have. i.e. my nav menu has display issues because the snipcart JS seems to be causing problems regarding load order.

**Comment by flozero** [comment]
thank you @gkurl I will close for now and see how to explain or implement this on the nuxt 3 version
