### ISSUE TITLE
Changes on customize.js not dispatch Nuxt Hot Reload flow

### ISSUE THREAD

**Issue by filippolcr** [nuxt-community/snipcart-module#6]
Hi, thanks for the module. It's simply great. 🙏

Just read the docs and trying to override a template, in this case <billing></billing>

When I edit something and perform a save, hot reload doesn't happen.

I've to rebuild manually nuxt to see the changes.

is this the expected behavior? Probably, for this kind of changes it is the only way forward. I do not know. Thanks 🤙🏻

**Comment by f3ltron** [comment]
Good point @filippolcr. I am happy you like the plugin. 

I will check about it this weekend. I will keep you up to date

**Comment by f3ltron** [comment]
It take me a bit more time than i thought to work on it but I didn't forget ! :)

**Comment by f3ltron** [comment]
normally version 1.1.0 resolve the issue @filippolcr  can you validate it please.

On js file you have to reload page. But on css it should just hot reload if you put it on the same customize folder

**Comment by filippolcr** [comment]
Ehi f3ltron,

thanks for your work. I update you in the next few days.

🤙🏻

**Comment by chrispreisler** [comment]
Hey guys, 

unfortunately the hmr/page reload is not working any more. I also have to restart the whole server to make changes.

Would love, if you have the time to look into that. Is it working on your site?

Thanks so much.

Best regards
Chris

**Comment by f3ltron** [comment]
It was working for me. I will have a look when I can
